### PR TITLE
Added fuzzy matching jeroenvisser101/project-switcher#4

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@CasperCLD thanks for your effort! I was actually thinking about porting the code from [Symfony/Console' find method](https://github.com/symfony/console/blob/master/Application.php#L485-L529), but this is a great start. I'll test this in a moment and then merge

**Comment by jeroenvisser101** [comment]
Works like a charm, thanks!

**Comment by ghost** [comment]
My pleasure! I might look into the Symfony/Console find method next weekend if I can 'find' me (pun intended) some spare time.

**Comment by jeroenvisser101** [comment]
Hehe, you're more than welcome to, of course :+1:

**Pull request merged**
